galaxy_info:
  author: antoon vereecken
  description: install i2p on a monero node
  company: AP Hogeschool (student)
  license: GPL-2.0-or-later, MIT, etc

  min_ansible_version: "2.1"

  platforms:
    - name: Debian
      versions:
        - all

  galaxy_tags: []

dependencies: []
  # - name: geerlingguy.docker