---
- name: Update packages
  ansible.builtin.package:
    name: '*'
    state: latest
    update_cache: yes
  when: ansible_os_family == "Debian"
  
- name: Install Tor
  ansible.builtin.package:
    name: tor
    state: present
  when: ansible_os_family == "Debian"

- name: Start and enable Tor
  ansible.builtin.service:
    name: tor
    state: started
    enabled: yes
  when: ansible_os_family == "Debian"

- name: Copy over torrc
  ansible.builtin.copy:
    src: torrc
    dest: /etc/tor/torrc
    owner: root
    group: root
    mode: '0644'
  when: ansible_os_family == "Debian"

- name: Restart Tor
  ansible.builtin.service:
    name: tor
    state: restarted
  when: ansible_os_family == "Debian"